core/iterable/iterable.go
core/iterable/mapiterable.go
core/iterable/mapiterable_test.go
go.mod

Might be useful to iterate maps as well
- Adds two value iterator with functions to go to and from maps
- Note that maps require comparable for keys, but there might be cases where you still want an iterator, so the iterator constraint is any/any while the map conversion functions are comparable/any
- Minor type improvement on original iterable
- We should really get rid of these when go 1.23 comes out. It has all these functions built in
- What's the deal with ucanto being a bucket for various forms of language and library DX improvements? IOW, we have our own little adds to IPLD, CAR, go lang / js itself all in a library for UCANs. It seems a little odd and I wonder if it makes sense to break it out as seperate packages? I guess on JS side maybe it is. Like I said just seems odd.

Add two value iterable for maps

---

core/ipld/rebind.go
core/ipld/rebind_test.go
core/schema/struct.go
core/schema/struct_test.go
server/server_test.go

- create a much simpler generic interface for rebind and simplify body as well
- remove copy/paste of bindnode.verifycompatibilty -- the proper way to do this is to check the err value on nodebuilder.AssignNode -- this operation will fail is the node structure is not compatible
- remove the additional copy paste from unmarshal streaming. All the fancy reflection basically to extract the copy of the struct built with prototype.NewBuilder and assign it to the pointer value for passed to the function. The simple fix is just lose the pointer value passed, and instead return the new copy. This didn't used to be possible cause of lack of generics, but you can do it now pretty easy.
- modify the Struct code to use the new version of rebind.
- also: the struct code contained a hidden assumption, …

Optimizations for rebind

---

did/did.go
principal/multiformat/multiformat.go
principal/multiformat/multiformat_test.go
principal/rsa/signer/signer.go
principal/rsa/signer/signer_test.go
principal/rsa/verifier/verifier.go
principal/rsa/verifier/verifier_test.go
ucan/crypto/signature/signature.go

This PR adds RSA key support. RSA keys are used on the browser since browsers do not yet support ed25519 keys (or at least support is patchy and not without bugs).
We'll likely only need RSA key _verification_ but for completeness this PR includes signing functionality also.

feat: add RSA key support

---

core/car/car.go
core/car/car_test.go
core/iterable/iterable.go

To feature complete blob index module in indexer-service, we need offset and length for each block when reading from a car, so that we can generate sharded dag index.
- Adds a small bit of CAR offfset math under the hood so that we can get block offsets and lengths
- Adds a tests that verifies these can be used to read exact blocks out of a CAR file
- Adds a small utility function to convert one Iterator to another (i.e. make an interator where each element is wrapped)

Car offsets

---

core/schema/link.go
core/schema/link_test.go
core/schema/mapped.go
core/schema/mapped_test.go
core/schema/or.go
core/schema/uri.go
core/schema/uri_test.go

More expressive schema languages. Adds Link, URI, and Or readers from js ucanto. Adds a "Mapped" reader for additional transformations (mostly on structs) and an initial read -- the reason here being that particularly in the case of structs, IPLD schemas may not always provide a schema def that is specific enough.
- add Mapped schema and test
- port js ucanto link schema and tests
- port js ucanto uri schema and tests
- port js ucanto or schema utility

More schema reader

---

principal/rsa/signer/signer.go

Copy pasta error. `0x1300` is Ed25519 signer code not RSA.
https://github.com/storacha/ucanto/blob/6de27c0f19790d9def1df2f2e299fa4f0996ded9/packages/principal/src/rsa/private-key.js#L8
Note: this was uncovered by [ucanto compatibility tests](https://github.com/storacha/ucanto-compat).

fix: RSA signer code

---

principal/ed25519/signer/signer.go
principal/ed25519/signer/signer_test.go
principal/lib.go
principal/rsa/signer/signer.go
principal/signer/signer.go

This PR adds a `Raw()` method to `Signer`, which allows encoding the private key without multiformats tags.
It effectively allows a signer generated here to interop with Go `crypto` and libp2p crypto.
The `Signature` type _already_ has a `Raw()` method (which does the same thing) so this is in keeping with that.

feat: raw signer

---

core/ipld/rebind.go
core/ipld/rebind_test.go

This PR allows `Rebind` to work on `schema.TypedNode`. This was a hidden error because oftentimes the representation form is compatible with the typed form. However when you start to use custom representations e.g. tuple, then `Rebind` will not work, since the `datamodel.Node` will have a map, when represented type expects a list.
The solution is to simply convert a `TypedNode` to it's representation form prior to binding to the type.
This is likely not used very often - if you have a _typed_ node then you have/had it in it's native Go type at some point, so you shouldn't need to rebind. This is however seen it tests, when a server is invoked by a client without serializing/deserializing capability caveats - and the validator has to parse already parsed caveats.

fix: rebind a typed node

---

core/result/ok/datamodel/unit.go
core/result/ok/datamodel/unit.ipldsch
core/result/ok/unit.go
core/result/ok/unit_test.go

This PR adds a utility type that makes it easier to return no data from a capability handler.

feat: add unit result type

---

core/delegation/delegate.go
core/delegation/delegation.go
core/delegation/delegation_test.go
core/invocation/invocation.go
testing/helpers/helpers.go
validator/lib_test.go

This PR adds a method `Attach` to `Delegation` that allows additional blocks to be attached. The primary usecase is to allow blocks linked from capabilities or facts to be included in the delegation payload.
Note: this feature exists in JS Ucanto already and it actually validates the blocks you attach are referenced from capabilities/facts. I will open an issue to track feature parity here assuming this is approved.

feat: attach blocks to delegation

---

core/receipt/fx/fx.go
core/receipt/receipt.go
core/receipt/receipt_test.go
server/handler.go
server/server.go
server/server_test.go
server/transaction/transaction.go

This PR allows completed effects to be included in a receipt. Similar to [`Ran`](https://github.com/storacha/go-ucanto/blob/main/core/invocation/ran/ran.go), an effect is now a union type - a link OR an invocation.
This allows a location commitment to be returned from a `blob/accept` invocation. 🤔 Not sure I agree with using effects for this, but this is how it is done currently.

feat: support invocations as effects

---

core/ipld/block/block.go
core/ipld/codec/cbor/cbor.go
core/ipld/codec/codec.go
core/ipld/codec/json/json.go
core/ipld/lib.go
core/ipld/rebind.go
core/receipt/receipt.go
core/schema/options/options.go
core/schema/struct.go

Improve ergonomics of working with schemas and structs with bindnode options
So here's the thing: I hade the Model extra copies being everywhere. It's fine when it's a complex class wrapping a model like in receipt, but a LOT of boilerplate when we're dealing with value objects -- namely capabilities and ok / err types on results. The thing is, most of these value objects can be used directly instead of having second version if they had just a little more logic around conversion from schemas. Fortunately, IPLD's bindnode actually has that through bindnode options, which while they're marked experimental, have been around for years and @rvagg just accepted my PR to make them work on named schema types, which means you can do a LOT with them. 
So, this PR basically just passes around …

feat(ipld): pass bindnode opts

---

core/result/failure/faillure.go

When unwrap results with fdm.FailureModel and wanting to generate an actual failure error, we need to recognize the zero value of fdm.Failure model as a non-error (especially with result.Map)

fix(failure): recognize non-failures

---

.github/workflows/test.yml
go.mod

upload test coverage results to Codecov and tidy CI config a bit
ref: https://github.com/storacha/project-tracking/issues/173

ci(github): set up codecov

---

did/did.go
principal/ed25519/signer/signer.go
principal/ed25519/signer/signer_test.go
principal/ed25519/verifier/verifier.go
principal/ed25519/verifier/verifier_test.go
principal/rsa/signer/signer.go
principal/rsa/signer/signer_test.go
principal/rsa/verifier/verifier.go
principal/rsa/verifier/verifier_test.go

This PR adds a `FromRaw([]byte)` function to ed25519 and RSA signers and verifiers. It is a compliment to the `.Raw()` interface function that `Signer` and `Verifier` has. It allows to round trip to/from raw bytes (non-multiformats) and also create signers and verifiers from compatible raw public/private key bytes generated from other ed25519/RSA libraries.
For example, it allows an ed25519 private key created by the libp2p crypto library to be converted to a Ucanto signer.

feat: create ed25519 and RSA signer/verifier from raw public/private key bytes

---

server/error.go
server/handler.go
server/options.go
server/server.go
server/server_test.go

Part of https://github.com/storacha/go-ucanto/issues/35
This PR ports the changes added to the JS ucanto library here: https://github.com/storacha/ucanto/pull/371
It adds a new `WithAlternativeAudiences` option that can be used when creating the server to have it accept invocations targeted to audiences different from the server's main identity.

feat: alternative audiences

---

core/receipt/datamodel/anyresult.ipldsch
core/receipt/datamodel/receipt.go
core/receipt/datamodel/receipt_test.go
core/receipt/receipt.go
core/receipt/receipt_test.go

The API was missing a way of reading receipts in a generic way.
`NewAnyReceiptReader` will read receipts no matter what actual types `Result.ok` or `Result.error` are. Using it will give you `AnyReceipt`s, which can then be used with `Rebind` to get a receipt with specific types if needed once you know what they are.

fix: add AnyReceiptReader

---

ucan/ucan.go

AFAICT, this comment is wrong, but all the code is right. Several places this is used describe it as seconds, and the `exp` field in a delegation uses seconds. It's just the comment here at the type declaration that says milliseconds.

fix: `UTCUnixTimestamp` is used for seconds, actually

---

core/delegation/delegation.go
core/delegation/delegation_test.go

Fixes `Blocks()` function of a `Delegation` to include only the root block of the delegation, any (non-absent) proofs and any attached blocks. This is [consistent with the JS implementation](https://github.com/storacha/ucanto/blob/46612a897f3981dba272d19367fb75c6720a70cd/packages/core/src/delegation.js#L500).
Previously exporting delegation blocks would include ALL blocks in the blockstore used to instantiate the delegation. This prevents us from instantiating a delegation from a blockstore that contains multiple unrelated delegations or other blocks not relevant to the delegation.
As a bonus, the constructor is altered to fetch and decode the root block allowing it to fail with an error instead of failing later on property access and possibly causing a npe panic.

fix: export includes only delegation blocks

---

server/handler.go
server/options.go
server/server.go
server/server_test.go

This PR changes the server handler return types.
Previously a handler signature was:
```go
func[O any](Context, Capability[C], Invocation, InvocationContext) (O, fx.Effects, error)
```
It is now:
```go
func[O any, X failure.IPLDBuilderFailure](Context, Capability[C], Invocation, InvocationContext) (result.Result[O, X], fx.Effects, error)
```
i.e. Instead of returning a success value (`O`), it now returns a `result.Result[O, X]`.
This allows the handler to return a custom error in a `result.Result`. This is in the case where the error is _known_. Previously all errors would have a `name` of `HandlerExecutionError` and the actual error would be communicated in the `cause` property. This is awkward to unpack on the client, is redundant (every error is currently a `HandlerExecutionError`) and …

feat: custom failures

---

server/retrieval/server.go
server/server.go

pass the request context object to the receipt logging function so that it can be propagated to things it calls

fix: pass context to receipt logging function
